version: '3.8'

services:
  db2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lutton_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3308"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  crawler:
    build:
      context: .
    depends_on:
      - db2
    environment:
      DATABASE_HOST: db2
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: lutton_db
    restart: on-failure
    volumes:
      - .:/app
  

volumes:
  db_data: