# -*- coding: utf-8 -*-
"""Crawling_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cs6n_ASi2j2_5jLkkGhh3fHF_QAoE_Qx
"""

import pandas as pd
from datetime import datetime
import requests
from bs4 import BeautifulSoup
import json

url = "https://www.10000recipe.com/ranking/home_new.html?rtype=k&dtype=d"
response = requests.get(url)

if response.status_code == 200:
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    script_tag = soup.find('script', {'type': 'application/ld+json'})
    soup = BeautifulSoup(response.content, 'html.parser')

    # 랭킹 데이터를 담을 리스트 초기화
    rankings = []

    # 랭킹 목록 찾기
    ranking_list = soup.find('ul', class_='goods_best3_1')

    # 랭킹 항목 순회
    for item in ranking_list.find_all('li'):
        rank = item.find('p', class_='ranking_num').text.strip()
        recipe_name = item.find('a').text.strip()
        recipe_link = item.find('a')['href']
        rankings.append({'rank': rank, 'name': recipe_name, 'link': recipe_link})

    # 결과 출력
    for rank in rankings:
        print(f"Rank: {rank['rank']}, Name: {rank['name']}, Link: {rank['link']}")

else:
  print("123")

          # dietaryFiber = json_data.get('nutrition', {}).get('fiberContent')